# Generated by Django 6.0.3 on 2026-04-03 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_created_at',
            new_name='reset_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
